### ISSUE TITLE
undefined is not a function (functions must be bound by 'request').

### ISSUE THREAD

**Issue by noseglid** [request/request#1506]
This worked in v2.53.0

```javascript
var Promise = require('bluebird');
var postAsync = Promise.promisify(require('request').post);

postAsync('http://www.google.com').then(function (content) {
  console.log(content);
});
```

in v2.54.0, above code gives this error:

```
Unhandled rejection TypeError: undefined is not a function
    at request.(anonymous function) (/home/alexo/tmp/node_modules/request/index.js:64:16)
    at tryCatcher (/home/alexo/tmp/node_modules/bluebird/js/main/util.js:24:31)
    at ret (eval at <anonymous> (/home/alexo/tmp/node_modules/bluebird/js/main/promisify.js:154:12), <anonymous>:13:23)
    at Object.<anonymous> (/home/alexo/tmp/a.js:4:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Any ideas what changes might've caused this?

**Comment by nicolasmccurdy** [comment]
I assume your file is `/home/alexo/tmp/a.js`?

**Comment by noseglid** [comment]
Investigated this a bit more. It seems that request.[verb] now requires it to be bound by 'request'.

This example doesn't work either:

```javascript
var post = require('request').post;
post('http://www.google.com', function (err, response, body) {
  console.log(body);
});
```

output:
```javascript

/home/alexo/tmp/node_modules/request/index.js:65
    return this(params.uri || null, params.options, params.callback)
               ^
TypeError: undefined is not a function
    at request.(anonymous function) (/home/alexo/tmp/node_modules/request/index.js:65:16)
    at Object.<anonymous> (/home/alexo/tmp/a.js:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```


The promisifying can be solved by doing: `var postAsync = Promise.promisify(require('request').post.bind(request))` . Then it works.

**Comment by ericlu88** [comment]
+1 for experiencing the same problem. The change seems to be introduced in #1430

**Comment by carsy** [comment]
:+1: same here

**Comment by simov** [comment]
Thanks everyone for the thorough bug report. Fixed here https://github.com/request/request/pull/1515 can you give it a try?

**Comment by noseglid** [comment]
@simov :+1: It fixes the issue.

**Comment by simov** [comment]
Nice! I'll merge it shortly.

**Comment by kytwb** [comment]
Can we get a release for this asap?
